# Generated by Django 4.2.1 on 2023-05-15 09:09

import JoDate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.CharField(default='000000000', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(default='00000000', max_length=255)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', 'Non-binary')], max_length=1)),
                ('department', models.CharField(max_length=255)),
                ('credit', models.PositiveIntegerField(default=100)),
                ('self_intro', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='000000000', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('A', '聯誼'), ('B', '打球'), ('C', '拼車'), ('D', '拚外送'), ('O', '其他')], max_length=1)),
                ('location', models.CharField(default='政大正門校碑', max_length=255)),
                ('date', models.DateTimeField(default=JoDate.models.Group.now_plus_30)),
                ('info', models.CharField(blank=True, max_length=255)),
                ('min_require', models.PositiveIntegerField(default=1)),
                ('max_require', models.PositiveIntegerField(default=10)),
                ('actual', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('FU', '目前額滿'), ('A', '尚有餘額'), ('C', '已經結束'), ('FA', '未成團'), ('NA', '已被刪除')], default='A', max_length=255)),
                ('User', models.ManyToManyField(to='JoDate.users')),
            ],
        ),
    ]
